from typing import Optional
from datetime import datetime
from sqlalchemy import (
    String, Boolean, Integer, Numeric, Text, JSON, DateTime,
    Index, ForeignKey, Enum as SQLEnum
)
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.dialects.postgresql import UUID
import uuid
from enum import Enum as PyEnum

from app.core.database import Base
from app.domains.shared.models import IDMixin, AuditMixin, SoftDeleteMixin


class TransactionStatus(PyEnum):
    """Transaction status following M-Pesa Daraja flow"""
    PENDING = "pending"  # STK Push initiated, awaiting user response
    AWAITING_USER_ACTION = "awaiting_user_action"  # User phone prompted, waiting
    COMPLETED = "completed"  # Payment successful
    FAILED = "failed"  # Payment failed
    CANCELLED = "cancelled"  # User cancelled
    EXPIRED = "expired"  # Request timeout (typically 5 minutes)
    REVERSED = "reversed"  # Transaction reversed (refund/chargeback)
    PROCESSING_REFUND = "processing_refund"
    REFUNDED = "refunded"


class TransactionType(PyEnum):
    """Transaction types"""
    PAYMENT = "payment"  # Customer paying for order
    REFUND = "refund"  # Refund to customer
    REVERSAL = "reversal"  # System reversal
    ADJUSTMENT = "adjustment"  # Manual adjustment


class Transaction(Base, IDMixin, AuditMixin, SoftDeleteMixin):
    """
    Payment transaction records.

    Follows M-Pesa Daraja API flow:
    1. STK Push initiated -> PENDING
    2. Customer receives prompt -> AWAITING_USER_ACTION
    3. Customer enters PIN -> processing
    4. Callback received -> COMPLETED or FAILED
    """
    __tablename__ = "transactions"
    __table_args__ = (
        Index("ix_transactions_status", "status"),
        Index("ix_transactions_merchant_request", "merchant_request_id"),
        Index("ix_transactions_checkout_request", "checkout_request_id"),
        Index("ix_transactions_phone", "phone_number"),
        Index("ix_transactions_order", "order_id"),
        Index("ix_transactions_date", "transaction_date"),
        Index("ix_transactions_status_deleted", "status", "is_deleted"),
    )

    # ===============================
    # REFERENCES
    # ===============================
    payment_method_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("payment_methods.id", ondelete="RESTRICT"),
        nullable=False,
        index=True
    )
    order_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        nullable=True
    )  # Link to order when implemented
    vendor_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        nullable=True,
        index=True
    )  # For vendor-specific transactions

    # ===============================
    # TRANSACTION TYPE & STATUS
    # ===============================
    transaction_type: Mapped[str] = mapped_column(
        String(20),
        default=TransactionType.PAYMENT.value,
        nullable=False,
        index=True
    )
    status: Mapped[str] = mapped_column(
        String(30),
        default=TransactionStatus.PENDING.value,
        nullable=False
    )

    # ===============================
    # AMOUNTS
    # ===============================
    amount: Mapped[float] = mapped_column(
        Numeric(12, 2),
        nullable=False
    )
    currency: Mapped[str] = mapped_column(
        String(3),
        default="KES",
        nullable=False
    )
    fee: Mapped[Optional[float]] = mapped_column(
        Numeric(12, 2),
        nullable=True
    )  # Payment method fee charged
    total_amount: Mapped[Optional[float]] = mapped_column(
        Numeric(12, 2),
        nullable=True
    )  # amount + fee

    # ===============================
    # M-PESA DARAJA FIELDS (Simulation)
    # ===============================
    merchant_request_id: Mapped[Optional[str]] = mapped_column(
        String(100),
        nullable=True,
        unique=True
    )  # Generated by us, sent to Daraja
    checkout_request_id: Mapped[Optional[str]] = mapped_column(
        String(100),
        nullable=True
    )  # Received from Daraja

    # Customer details
    phone_number: Mapped[str] = mapped_column(
        String(20),
        nullable=False
    )  # Format: 254XXXXXXXXX

    # ===============================
    # RESPONSE DATA (From Daraja)
    # ===============================
    response_description: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True
    )  # Human-readable response
    response_code: Mapped[Optional[str]] = mapped_column(
        String(10),
        nullable=True
    )  # Daraja response code

    customer_message: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True
    )  # Message sent to customer's phone

    # ===============================
    # COMPLETED TRANSACTION DATA
    # ===============================
    mpesa_receipt: Mapped[Optional[str]] = mapped_column(
        String(100),
        nullable=True,
        unique=True
    )  # M-Pesa transaction receipt number
    transaction_date: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True
    )  # When payment was completed
    balance: Mapped[Optional[float]] = mapped_column(
        Numeric(12, 2),
        nullable=True
    )  # Account balance after transaction (simulated)

    # ===============================
    # METADATA
    # ===============================
    ip_address: Mapped[Optional[str]] = mapped_column(
        String(50),
        nullable=True
    )  # Customer IP for fraud detection
    user_agent: Mapped[Optional[str]] = mapped_column(
        String(500),
        nullable=True
    )

    # Additional context
    transaction_metadata: Mapped[Optional[dict]] = mapped_column(JSON, nullable=True)
    notes: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # Failure tracking
    failure_reason: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True
    )
    retry_count: Mapped[int] = mapped_column(
        Integer,
        default=0
    )
    max_retries_reached: Mapped[bool] = mapped_column(
        Boolean,
        default=False
    )

    # ===============================
    # RELATIONSHIPS
    # ===============================
    payment_method: Mapped["PaymentMethod"] = relationship(
        "PaymentMethod",
        back_populates="transactions",
        lazy="selectin"
    )
    callbacks: Mapped[list["PaymentCallback"]] = relationship(
        "PaymentCallback",
        back_populates="transaction",
        cascade="all, delete-orphan",
        lazy="selectin"
    )
    refunds: Mapped[list["Refund"]] = relationship(
        "Refund",
        back_populates="transaction",
        cascade="all, delete-orphan",
        lazy="selectin"
    )

    def __repr__(self) -> str:
        return f"<Transaction {self.merchant_request_id or self.id} - {self.status} - {self.currency} {self.amount}>"
