"""Add reviews relationship to Product model

Revision ID: 0c55ca2ff767
Revises: d6dd9df83d7b
Create Date: 2026-08-05 13:54:25.993035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c55ca2ff767'
down_revision: Union[str, Sequence[str], None] = 'd6dd9df83d7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
