"""Add shopping domain tables

Revision ID: 24a7725d1ae0
Revises: bfe4925baf5d
Create Date: 2026-06-13 15:35:12.065977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24a7725d1ae0'
down_revision: Union[str, Sequence[str], None] = 'bfe4925baf5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carts',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('cart_token', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('cart_type', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carts_cart_token'), 'carts', ['cart_token'], unique=True)
    op.create_index(op.f('ix_carts_expires_at'), 'carts', ['expires_at'], unique=False)
    op.create_index(op.f('ix_carts_is_active'), 'carts', ['is_active'], unique=False)
    op.create_index(op.f('ix_carts_session_id'), 'carts', ['session_id'], unique=True)
    op.create_index(op.f('ix_carts_user_id'), 'carts', ['user_id'], unique=False)
    op.create_table('saved_carts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_carts_user_id'), 'saved_carts', ['user_id'], unique=False)
    op.create_table('cart_discounts',
    sa.Column('cart_id', sa.UUID(), nullable=False),
    sa.Column('coupon_code', sa.String(length=100), nullable=True),
    sa.Column('promotion_id', sa.String(length=100), nullable=True),
    sa.Column('discount_type', sa.String(length=50), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_applied', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_discounts_cart_id'), 'cart_discounts', ['cart_id'], unique=False)
    op.create_index(op.f('ix_cart_discounts_coupon_code'), 'cart_discounts', ['coupon_code'], unique=False)
    op.create_table('cart_merge_logs',
    sa.Column('source_cart_id', sa.UUID(), nullable=True),
    sa.Column('target_cart_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('merge_method', sa.String(length=50), nullable=False),
    sa.Column('source_item_count', sa.Integer(), nullable=False),
    sa.Column('target_item_count_before', sa.Integer(), nullable=False),
    sa.Column('target_item_count_after', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_cart_id'], ['carts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_cart_id'], ['carts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_merge_logs_user_id'), 'cart_merge_logs', ['user_id'], unique=False)
    op.create_table('cart_shares',
    sa.Column('cart_id', sa.UUID(), nullable=False),
    sa.Column('share_token', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_shares_cart_id'), 'cart_shares', ['cart_id'], unique=False)
    op.create_index(op.f('ix_cart_shares_expires_at'), 'cart_shares', ['expires_at'], unique=False)
    op.create_index(op.f('ix_cart_shares_share_token'), 'cart_shares', ['share_token'], unique=True)
    op.create_table('coupons',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('coupon_type', sa.String(length=50), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_scope', sa.String(length=50), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_stackable', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('distribution_type', sa.String(length=50), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupons_code'), 'coupons', ['code'], unique=True)
    op.create_index(op.f('ix_coupons_is_active'), 'coupons', ['is_active'], unique=False)
    op.create_index(op.f('ix_coupons_valid_from'), 'coupons', ['valid_from'], unique=False)
    op.create_index(op.f('ix_coupons_valid_until'), 'coupons', ['valid_until'], unique=False)
    op.create_index(op.f('ix_coupons_vendor_id'), 'coupons', ['vendor_id'], unique=False)
    op.create_table('cart_items',
    sa.Column('cart_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('substitution_allowed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_items_cart_id'), 'cart_items', ['cart_id'], unique=False)
    op.create_index(op.f('ix_cart_items_product_id'), 'cart_items', ['product_id'], unique=False)
    op.create_table('coupon_categories',
    sa.Column('coupon_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupon_categories_category'), 'coupon_categories', ['category'], unique=False)
    op.create_index(op.f('ix_coupon_categories_coupon_id'), 'coupon_categories', ['coupon_id'], unique=False)
    op.create_table('coupon_products',
    sa.Column('coupon_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupon_products_coupon_id'), 'coupon_products', ['coupon_id'], unique=False)
    op.create_index(op.f('ix_coupon_products_product_id'), 'coupon_products', ['product_id'], unique=False)
    op.create_table('coupon_restrictions',
    sa.Column('coupon_id', sa.UUID(), nullable=False),
    sa.Column('min_order_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_discount_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('new_users_only', sa.Boolean(), nullable=False),
    sa.Column('first_purchase_only', sa.Boolean(), nullable=False),
    sa.Column('one_time_per_user', sa.Boolean(), nullable=False),
    sa.Column('global_usage_limit', sa.Integer(), nullable=True),
    sa.Column('vendor_only', sa.Boolean(), nullable=False),
    sa.Column('exclude_sale_items', sa.Boolean(), nullable=False),
    sa.Column('buy_product_id', sa.UUID(), nullable=True),
    sa.Column('buy_quantity', sa.Integer(), nullable=True),
    sa.Column('get_product_id', sa.UUID(), nullable=True),
    sa.Column('get_quantity', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['buy_product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['get_product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupon_restrictions_coupon_id'), 'coupon_restrictions', ['coupon_id'], unique=True)
    op.create_table('coupon_usages',
    sa.Column('coupon_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_refunded', sa.Boolean(), nullable=False),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupon_usages_coupon_id'), 'coupon_usages', ['coupon_id'], unique=False)
    op.create_index(op.f('ix_coupon_usages_order_id'), 'coupon_usages', ['order_id'], unique=False)
    op.create_index(op.f('ix_coupon_usages_user_id'), 'coupon_usages', ['user_id'], unique=False)
    op.create_index(op.f('ix_coupon_usages_vendor_id'), 'coupon_usages', ['vendor_id'], unique=False)
    op.create_table('saved_cart_items',
    sa.Column('saved_cart_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['saved_cart_id'], ['saved_carts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_cart_items_product_id'), 'saved_cart_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_saved_cart_items_saved_cart_id'), 'saved_cart_items', ['saved_cart_id'], unique=False)
    op.create_table('user_coupons',
    sa.Column('coupon_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_coupons_coupon_id'), 'user_coupons', ['coupon_id'], unique=False)
    op.create_index(op.f('ix_user_coupons_user_id'), 'user_coupons', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_coupons_user_id'), table_name='user_coupons')
    op.drop_index(op.f('ix_user_coupons_coupon_id'), table_name='user_coupons')
    op.drop_table('user_coupons')
    op.drop_index(op.f('ix_saved_cart_items_saved_cart_id'), table_name='saved_cart_items')
    op.drop_index(op.f('ix_saved_cart_items_product_id'), table_name='saved_cart_items')
    op.drop_table('saved_cart_items')
    op.drop_index(op.f('ix_coupon_usages_vendor_id'), table_name='coupon_usages')
    op.drop_index(op.f('ix_coupon_usages_user_id'), table_name='coupon_usages')
    op.drop_index(op.f('ix_coupon_usages_order_id'), table_name='coupon_usages')
    op.drop_index(op.f('ix_coupon_usages_coupon_id'), table_name='coupon_usages')
    op.drop_table('coupon_usages')
    op.drop_index(op.f('ix_coupon_restrictions_coupon_id'), table_name='coupon_restrictions')
    op.drop_table('coupon_restrictions')
    op.drop_index(op.f('ix_coupon_products_product_id'), table_name='coupon_products')
    op.drop_index(op.f('ix_coupon_products_coupon_id'), table_name='coupon_products')
    op.drop_table('coupon_products')
    op.drop_index(op.f('ix_coupon_categories_coupon_id'), table_name='coupon_categories')
    op.drop_index(op.f('ix_coupon_categories_category'), table_name='coupon_categories')
    op.drop_table('coupon_categories')
    op.drop_index(op.f('ix_cart_items_product_id'), table_name='cart_items')
    op.drop_index(op.f('ix_cart_items_cart_id'), table_name='cart_items')
    op.drop_table('cart_items')
    op.drop_index(op.f('ix_coupons_vendor_id'), table_name='coupons')
    op.drop_index(op.f('ix_coupons_valid_until'), table_name='coupons')
    op.drop_index(op.f('ix_coupons_valid_from'), table_name='coupons')
    op.drop_index(op.f('ix_coupons_is_active'), table_name='coupons')
    op.drop_index(op.f('ix_coupons_code'), table_name='coupons')
    op.drop_table('coupons')
    op.drop_index(op.f('ix_cart_shares_share_token'), table_name='cart_shares')
    op.drop_index(op.f('ix_cart_shares_expires_at'), table_name='cart_shares')
    op.drop_index(op.f('ix_cart_shares_cart_id'), table_name='cart_shares')
    op.drop_table('cart_shares')
    op.drop_index(op.f('ix_cart_merge_logs_user_id'), table_name='cart_merge_logs')
    op.drop_table('cart_merge_logs')
    op.drop_index(op.f('ix_cart_discounts_coupon_code'), table_name='cart_discounts')
    op.drop_index(op.f('ix_cart_discounts_cart_id'), table_name='cart_discounts')
    op.drop_table('cart_discounts')
    op.drop_index(op.f('ix_saved_carts_user_id'), table_name='saved_carts')
    op.drop_table('saved_carts')
    op.drop_index(op.f('ix_carts_user_id'), table_name='carts')
    op.drop_index(op.f('ix_carts_session_id'), table_name='carts')
    op.drop_index(op.f('ix_carts_is_active'), table_name='carts')
    op.drop_index(op.f('ix_carts_expires_at'), table_name='carts')
    op.drop_index(op.f('ix_carts_cart_token'), table_name='carts')
    op.drop_table('carts')
    # ### end Alembic commands ###
