"""add_order_timeline_event

Revision ID: 3ea050a8e91b
Revises: 9228d5f8fa32
Create Date: 2026-06-26 15:53:48.069223

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3ea050a8e91b'
down_revision: Union[str, Sequence[str], None] = '9228d5f8fa32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_timeline_events',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_timeline_events_order_id'), 'order_timeline_events', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_timeline_events_status'), 'order_timeline_events', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_timeline_events_status'), table_name='order_timeline_events')
    op.drop_index(op.f('ix_order_timeline_events_order_id'), table_name='order_timeline_events')
    op.drop_table('order_timeline_events')
    # ### end Alembic commands ###
