"""add_loyalty_discount_to_orders

Revision ID: 50eb45e3690b
Revises: d197c342c01a
Create Date: 2026-08-11 18:04:51.941501

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '50eb45e3690b'
down_revision: Union[str, Sequence[str], None] = 'd197c342c01a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('loyalty_discount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('orders', sa.Column('loyalty_points_redeemed', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'loyalty_points_redeemed')
    op.drop_column('orders', 'loyalty_discount')
    # ### end Alembic commands ###
