"""add_product_type_variants_bundles_related

Revision ID: 5c078812e087
Revises: d59e7e7fcc05
Create Date: 2026-08-11 11:22:15.981854

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5c078812e087'
down_revision: Union[str, Sequence[str], None] = 'd59e7e7fcc05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bundle_items',
    sa.Column('bundle_product_id', sa.UUID(), nullable=False),
    sa.Column('component_product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bundle_product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['component_product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bundle_items_bundle_product_id'), 'bundle_items', ['bundle_product_id'], unique=False)
    op.create_index(op.f('ix_bundle_items_component_product_id'), 'bundle_items', ['component_product_id'], unique=False)
    op.create_table('related_products',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('related_product_id', sa.UUID(), nullable=False),
    sa.Column('relation_type', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_bidirectional', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'related_product_id', 'relation_type', name='uq_related_products_pair_type')
    )
    op.create_index(op.f('ix_related_products_product_id'), 'related_products', ['product_id'], unique=False)
    op.create_index(op.f('ix_related_products_related_product_id'), 'related_products', ['related_product_id'], unique=False)
    op.create_index(op.f('ix_related_products_relation_type'), 'related_products', ['relation_type'], unique=False)
    op.add_column('product_variants', sa.Column('override_price', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('product_variants', sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('product_variants', sa.Column('image_url', sa.String(length=1000), nullable=True))
    op.add_column('product_variants', sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False))
    op.add_column('product_variants', sa.Column('weight_kg', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('product_type', sa.String(length=20), server_default='simple', nullable=False))
    op.create_index(op.f('ix_products_product_type'), 'products', ['product_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_product_type'), table_name='products')
    op.drop_column('products', 'product_type')
    op.drop_column('product_variants', 'weight_kg')
    op.drop_column('product_variants', 'sort_order')
    op.drop_column('product_variants', 'image_url')
    op.drop_column('product_variants', 'is_default')
    op.drop_column('product_variants', 'override_price')
    op.drop_index(op.f('ix_related_products_relation_type'), table_name='related_products')
    op.drop_index(op.f('ix_related_products_related_product_id'), table_name='related_products')
    op.drop_index(op.f('ix_related_products_product_id'), table_name='related_products')
    op.drop_table('related_products')
    op.drop_index(op.f('ix_bundle_items_component_product_id'), table_name='bundle_items')
    op.drop_index(op.f('ix_bundle_items_bundle_product_id'), table_name='bundle_items')
    op.drop_table('bundle_items')
    # ### end Alembic commands ###
