"""add internal_notes to orders

Revision ID: 5e11bc00e9f3
Revises: affdb016b2a7
Create Date: 2026-07-30 13:58:15.167287

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5e11bc00e9f3'
down_revision: Union[str, Sequence[str], None] = 'affdb016b2a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('internal_notes', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'internal_notes')
    # ### end Alembic commands ###
