"""add_indexes_and_constraints

Revision ID: 647c4641ede8
Revises: 94db97a818d4
Create Date: 2026-06-11 13:39:37.699025

"""
from collections.abc import Sequence
from typing import Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '647c4641ede8'
down_revision: Union[str, Sequence[str], None] = '94db97a818d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_otps_user_purpose_used', 'otps', ['user_id', 'purpose', 'is_used'], unique=False)
    op.create_index('idx_products_status_deleted', 'products', ['status', 'is_deleted'], unique=False)
    op.create_index('idx_refresh_tokens_user_expires', 'refresh_tokens', ['user_id', 'expires_at'], unique=False)
    op.create_check_constraint(
        "check_user_role",
        "users",
        "role IN ('admin', 'worker', 'vendor', 'customer', 'guest')"
    )
    op.create_check_constraint(
        "check_user_email_format",
        "users",
        "email LIKE '%@%.%'"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("check_user_email_format", "users", type_="check")
    op.drop_constraint("check_user_role", "users", type_="check")
    op.drop_index('idx_refresh_tokens_user_expires', table_name='refresh_tokens')
    op.drop_index('idx_products_status_deleted', table_name='products')
    op.drop_index('idx_otps_user_purpose_used', table_name='otps')
    # ### end Alembic commands ###
