"""Add returns and payment methods domains

Revision ID: 887949e61f26
Revises: c14e00030e72
Create Date: 2026-06-15 10:04:13.621748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '887949e61f26'
down_revision: Union[str, Sequence[str], None] = 'c14e00030e72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create saved_payment_methods table
    op.create_table(
        'saved_payment_methods',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('customer_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('payment_type', sa.Enum('mpesa', 'card', 'bank_transfer', name='payment_type', create_type=False), nullable=False),
        sa.Column('is_default', sa.Boolean(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('phone_number', sa.String(length=20), nullable=True),
        sa.Column('card_token', sa.String(length=255), nullable=True),
        sa.Column('card_last4', sa.String(length=4), nullable=True),
        sa.Column('card_brand', sa.String(length=20), nullable=True),
        sa.Column('card_expiry_month', sa.String(length=2), nullable=True),
        sa.Column('card_expiry_year', sa.String(length=4), nullable=True),
        sa.Column('cardholder_name', sa.String(length=200), nullable=True),
        sa.Column('bank_name', sa.String(length=100), nullable=True),
        sa.Column('bank_account_number', sa.String(length=50), nullable=True),
        sa.Column('bank_account_name', sa.String(length=200), nullable=True),
        sa.Column('display_name', sa.String(length=100), nullable=True),
        sa.Column('metadata', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_payment_methods_customer_id'), 'saved_payment_methods', ['customer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_payment_methods_customer_id'), table_name='saved_payment_methods')
    op.drop_table('saved_payment_methods')
    # ### end Alembic commands ###
