"""Add WooCommerce migration fields

Revision ID: 91004e18ddae
Revises: 610c8967b51e
Create Date: 2026-06-14 06:44:46.131974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91004e18ddae'
down_revision: Union[str, Sequence[str], None] = '610c8967b51e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop old payment domain tables (in correct order due to foreign key dependencies)
    # 1. Drop payment_callbacks first (depends on transactions)
    op.drop_index(op.f('ix_payment_callbacks_merchant'), table_name='payment_callbacks')
    op.drop_index(op.f('ix_payment_callbacks_status'), table_name='payment_callbacks')
    op.drop_index(op.f('ix_payment_callbacks_transaction'), table_name='payment_callbacks')
    op.drop_table('payment_callbacks')

    # 2. Drop refunds (depends on transactions)
    op.drop_index(op.f('ix_refunds_date'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_order'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_status'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_status_deleted'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_transaction'), table_name='refunds')
    op.drop_table('refunds')

    # 3. Drop transactions (no more dependencies)
    op.drop_index(op.f('ix_transactions_checkout_request'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_merchant_request'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_order'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_phone'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_status_deleted'), table_name='transactions')
    op.drop_table('transactions')

    # 4. Drop payment_methods (no dependencies)
    op.drop_index(op.f('ix_payment_methods_provider_status'), table_name='payment_methods')
    op.drop_index(op.f('ix_payment_methods_status_deleted'), table_name='payment_methods')
    op.drop_table('payment_methods')

    # Add WooCommerce migration fields
    op.add_column('categories', sa.Column('permalink', sa.String(length=500), nullable=True))
    op.add_column('products', sa.Column('sale_price', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('products', sa.Column('stock_status', sa.String(length=20), nullable=False, server_default='instock'))
    op.add_column('products', sa.Column('permalink', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_products_stock_status'), 'products', ['stock_status'], unique=False)
    op.add_column('vendor_profiles', sa.Column('username', sa.String(length=100), nullable=True))
    op.add_column('vendor_profiles', sa.Column('display_name', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_vendor_profiles_username'), 'vendor_profiles', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendor_profiles_username'), table_name='vendor_profiles')
    op.drop_column('vendor_profiles', 'display_name')
    op.drop_column('vendor_profiles', 'username')
    op.drop_index(op.f('ix_products_stock_status'), table_name='products')
    op.drop_column('products', 'permalink')
    op.drop_column('products', 'stock_status')
    op.drop_column('products', 'sale_price')
    op.drop_column('categories', 'permalink')
    op.create_table('refunds',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('initiated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('reason', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('reason_details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), server_default=sa.text("'KES'::character varying"), autoincrement=False, nullable=True),
    sa.Column('refund_fee', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('net_refund', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('reversal_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('mpesa_receipt', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('initiated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('response_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('response_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('approved_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('approved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('approval_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('internal_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('failure_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('retry_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('refunds_transaction_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('refunds_pkey')),
    sa.UniqueConstraint('reversal_id', name=op.f('refunds_reversal_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_refunds_transaction'), 'refunds', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_refunds_status_deleted'), 'refunds', ['status', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_refunds_status'), 'refunds', ['status'], unique=False)
    op.create_index(op.f('ix_refunds_order'), 'refunds', ['order_id'], unique=False)
    op.create_index(op.f('ix_refunds_date'), 'refunds', ['initiated_at'], unique=False)
    op.create_table('payment_methods',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('is_default', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=True),
    sa.Column('mpesa_shortcode', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('mpesa_business_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('mpesa_environment', sa.VARCHAR(length=20), server_default=sa.text("'simulation'::character varying"), autoincrement=False, nullable=True),
    sa.Column('fee_type', sa.VARCHAR(length=20), server_default=sa.text("'percentage'::character varying"), autoincrement=False, nullable=True),
    sa.Column('fee_value', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0.0'), autoincrement=False, nullable=True),
    sa.Column('fee_min', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0.0'), autoincrement=False, nullable=True),
    sa.Column('fee_max', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('min_amount', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('1.0'), autoincrement=False, nullable=True),
    sa.Column('max_amount', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('150000.0'), autoincrement=False, nullable=True),
    sa.Column('processing_time_seconds', sa.INTEGER(), server_default=sa.text('30'), autoincrement=False, nullable=True),
    sa.Column('retry_count', sa.INTEGER(), server_default=sa.text('3'), autoincrement=False, nullable=True),
    sa.Column('display_order', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('icon_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('display_label', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('payment_methods_pkey'))
    )
    op.create_index(op.f('ix_payment_methods_status_deleted'), 'payment_methods', ['status', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_payment_methods_provider_status'), 'payment_methods', ['provider', 'status'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('payment_method_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('vendor_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('transaction_type', sa.VARCHAR(length=20), server_default=sa.text("'payment'::character varying"), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), server_default=sa.text("'KES'::character varying"), autoincrement=False, nullable=True),
    sa.Column('fee', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('merchant_request_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('checkout_request_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('response_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('response_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('customer_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mpesa_receipt', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('transaction_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('balance', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('failure_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('retry_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('max_retries_reached', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], name=op.f('transactions_payment_method_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('transactions_pkey')),
    sa.UniqueConstraint('merchant_request_id', name=op.f('transactions_merchant_request_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('mpesa_receipt', name=op.f('transactions_mpesa_receipt_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_transactions_status_deleted'), 'transactions', ['status', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    op.create_index(op.f('ix_transactions_phone'), 'transactions', ['phone_number'], unique=False)
    op.create_index(op.f('ix_transactions_order'), 'transactions', ['order_id'], unique=False)
    op.create_index(op.f('ix_transactions_merchant_request'), 'transactions', ['merchant_request_id'], unique=False)
    op.create_index(op.f('ix_transactions_date'), 'transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_transactions_checkout_request'), 'transactions', ['checkout_request_id'], unique=False)
    op.create_table('payment_callbacks',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('merchant_request_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('checkout_request_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('result_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('result_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('raw_callback', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('response_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('callback_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('verification_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('processing_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('retry_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('headers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('payment_callbacks_transaction_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('payment_callbacks_pkey'))
    )
    op.create_index(op.f('ix_payment_callbacks_transaction'), 'payment_callbacks', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_payment_callbacks_status'), 'payment_callbacks', ['status'], unique=False)
    op.create_index(op.f('ix_payment_callbacks_merchant'), 'payment_callbacks', ['merchant_request_id'], unique=False)
    # ### end Alembic commands ###
