"""Add banner and 
  promotion tables

Revision ID: 9d98d1af99e4
Revises: 0c55ca2ff767
Create Date: 2026-08-05 20:03:59.879411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d98d1af99e4'
down_revision: Union[str, Sequence[str], None] = '0c55ca2ff767'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banners',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('image_alt_text', sa.String(length=200), nullable=True),
    sa.Column('background_color', sa.String(length=20), nullable=True),
    sa.Column('text_color', sa.String(length=20), nullable=True),
    sa.Column('cta_text', sa.String(length=100), nullable=True),
    sa.Column('cta_link', sa.String(length=500), nullable=True),
    sa.Column('cta_target', sa.String(length=20), nullable=False),
    sa.Column('placement', sa.Enum('HOMEPAGE_HERO', 'HOMEPAGE_SIDEBAR', 'CATEGORY_PAGE', 'PRODUCT_PAGE', 'CHECKOUT_PAGE', 'HEADER_BAR', 'FOOTER', name='bannerplacement'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'ACTIVE', 'PAUSED', 'EXPIRED', name='bannerstatus'), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('target_audience', postgresql.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('target_categories', postgresql.ARRAY(sa.String(length=100)), nullable=True),
    sa.Column('target_products', postgresql.ARRAY(sa.String(length=100)), nullable=True),
    sa.Column('exclude_products', postgresql.ARRAY(sa.String(length=100)), nullable=True),
    sa.Column('coupon_id', sa.UUID(), nullable=True),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('is_dismissible', sa.Boolean(), nullable=False),
    sa.Column('show_close_button', sa.Boolean(), nullable=False),
    sa.Column('mobile_hidden', sa.Boolean(), nullable=False),
    sa.Column('desktop_hidden', sa.Boolean(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('dismissals', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_banners_coupon_id'), 'banners', ['coupon_id'], unique=False)
    op.create_index(op.f('ix_banners_placement'), 'banners', ['placement'], unique=False)
    op.create_index(op.f('ix_banners_scheduled_end'), 'banners', ['scheduled_end'], unique=False)
    op.create_index(op.f('ix_banners_scheduled_start'), 'banners', ['scheduled_start'], unique=False)
    op.create_index(op.f('ix_banners_status'), 'banners', ['status'], unique=False)
    op.create_index(op.f('ix_banners_vendor_id'), 'banners', ['vendor_id'], unique=False)
    op.create_table('banner_clicks',
    sa.Column('banner_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('referrer', sa.String(length=500), nullable=True),
    sa.Column('clicked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['banner_id'], ['banners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_banner_clicks_banner_id'), 'banner_clicks', ['banner_id'], unique=False)
    op.create_index(op.f('ix_banner_clicks_clicked_at'), 'banner_clicks', ['clicked_at'], unique=False)
    op.create_index(op.f('ix_banner_clicks_session_id'), 'banner_clicks', ['session_id'], unique=False)
    op.create_index(op.f('ix_banner_clicks_user_id'), 'banner_clicks', ['user_id'], unique=False)
    op.create_table('banner_dismissals',
    sa.Column('banner_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['banner_id'], ['banners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_banner_dismissals_banner_id'), 'banner_dismissals', ['banner_id'], unique=False)
    op.create_index(op.f('ix_banner_dismissals_session_id'), 'banner_dismissals', ['session_id'], unique=False)
    op.create_index(op.f('ix_banner_dismissals_user_id'), 'banner_dismissals', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_banner_dismissals_user_id'), table_name='banner_dismissals')
    op.drop_index(op.f('ix_banner_dismissals_session_id'), table_name='banner_dismissals')
    op.drop_index(op.f('ix_banner_dismissals_banner_id'), table_name='banner_dismissals')
    op.drop_table('banner_dismissals')
    op.drop_index(op.f('ix_banner_clicks_user_id'), table_name='banner_clicks')
    op.drop_index(op.f('ix_banner_clicks_session_id'), table_name='banner_clicks')
    op.drop_index(op.f('ix_banner_clicks_clicked_at'), table_name='banner_clicks')
    op.drop_index(op.f('ix_banner_clicks_banner_id'), table_name='banner_clicks')
    op.drop_table('banner_clicks')
    op.drop_index(op.f('ix_banners_vendor_id'), table_name='banners')
    op.drop_index(op.f('ix_banners_status'), table_name='banners')
    op.drop_index(op.f('ix_banners_scheduled_start'), table_name='banners')
    op.drop_index(op.f('ix_banners_scheduled_end'), table_name='banners')
    op.drop_index(op.f('ix_banners_placement'), table_name='banners')
    op.drop_index(op.f('ix_banners_coupon_id'), table_name='banners')
    op.drop_table('banners')
    # ### end Alembic commands ###
