"""add_missing_composite_indexes

Revision ID: a1922e3258f9
Revises: 647c4641ede8
Create Date: 2026-06-11 13:59:24.375185

"""
from collections.abc import Sequence
from typing import Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a1922e3258f9'
down_revision: Union[str, Sequence[str], None] = '647c4641ede8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_products_vendor_status_deleted', 'products', ['vendor_id', 'status', 'is_deleted'], unique=False)
    op.drop_index(op.f('idx_refresh_tokens_user_expires'), table_name='refresh_tokens')
    op.create_index('idx_refresh_tokens_user_expires', 'refresh_tokens', ['user_id', 'expires_at', 'revoked'], unique=False)
    op.create_index('idx_users_role_active', 'users', ['role', 'is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_users_role_active', table_name='users')
    op.drop_index('idx_refresh_tokens_user_expires', table_name='refresh_tokens')
    op.create_index(op.f('idx_refresh_tokens_user_expires'), 'refresh_tokens', ['user_id', 'expires_at'], unique=False)
    op.drop_index('idx_products_vendor_status_deleted', table_name='products')
    # ### end Alembic commands ###
