"""add vendor profile and vendor fields to user

Revision ID: e5f8a3b2c4d1
Revises: d93d78271ea6
Create Date: 2026-06-10 18:00:00.000000

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5f8a3b2c4d1'
down_revision: Union[str, Sequence[str], None] = 'd93d78271ea6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Add vendor-specific fields to users table
    op.add_column('users', sa.Column('company_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('vat_number', sa.String(length=50), nullable=True))

    # Create vendor_profiles table
    op.create_table(
        'vendor_profiles',
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),

        # Store Information
        sa.Column('store_name', sa.String(length=255), nullable=False),
        sa.Column('store_description', sa.Text(), nullable=True),
        sa.Column('store_logo_url', sa.String(length=500), nullable=True),
        sa.Column('business_email', sa.String(length=255), nullable=True),
        sa.Column('business_phone', sa.String(length=20), nullable=True),

        # Store Address (Google Places)
        sa.Column('address_street', sa.String(length=500), nullable=True),
        sa.Column('address_city', sa.String(length=100), nullable=True),
        sa.Column('address_region', sa.String(length=100), nullable=True),
        sa.Column('address_country', sa.String(length=2), nullable=True, server_default='KE'),
        sa.Column('latitude', sa.Float(), nullable=True),
        sa.Column('longitude', sa.Float(), nullable=True),
        sa.Column('place_id', sa.String(length=100), nullable=True),

        # Payment & Payout Details
        # M-Pesa
        sa.Column('mpesa_phone', sa.String(length=20), nullable=True),
        sa.Column('mpesa_business_name', sa.String(length=255), nullable=True),
        sa.Column('mpesa_till_number', sa.String(length=20), nullable=True),
        sa.Column('mpesa_paybill_number', sa.String(length=20), nullable=True),

        # Bank Account
        sa.Column('bank_account_name', sa.String(length=255), nullable=True),
        sa.Column('bank_account_number', sa.String(length=50), nullable=True),
        sa.Column('bank_name', sa.String(length=255), nullable=True),
        sa.Column('bank_branch', sa.String(length=255), nullable=True),
        sa.Column('bank_swift_code', sa.String(length=20), nullable=True),
        sa.Column('bank_iban', sa.String(length=50), nullable=True),

        # Operational Details
        sa.Column('business_hours', postgresql.JSON(), nullable=True),

        # Administrative Fields
        sa.Column('approval_status', sa.String(length=20), nullable=False, server_default='pending'),
        sa.Column('document_urls', postgresql.JSON(), nullable=True),
        sa.Column('company_name', sa.String(length=255), nullable=True),
        sa.Column('vat_number', sa.String(length=50), nullable=True),
        sa.Column('rejection_reason', sa.Text(), nullable=True),
        sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('approved_by', postgresql.UUID(as_uuid=True), nullable=True),

        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendor_profiles')
    op.drop_column('users', 'vat_number')
    op.drop_column('users', 'company_name')
    # ### end Alembic commands ###
