"""add mobile money payments

Revision ID: add_mobile_money_payments
Revises: d197c342c01a
Create Date: 2026-08-13 13:30:00.000000

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'add_mobile_money_payments'
down_revision: Union[str, Sequence[str], None] = 'd197c342c01a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create mobile_money_payments table
    op.create_table(
        'mobile_money_payments',
        sa.Column('order_id', sa.UUID(), nullable=False),
        sa.Column('transaction_id', sa.String(length=50), nullable=False),
        sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('currency', sa.String(length=3), nullable=False, server_default='KES'),
        sa.Column('provider', sa.String(length=50), nullable=False),
        sa.Column('phone_number', sa.String(length=20), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=False, server_default='verified'),
        sa.Column('refund_transaction_id', sa.String(length=50), nullable=True),
        sa.Column('refund_amount', sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column('refund_reason', sa.Text(), nullable=True),
        sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('refunded_by_id', sa.UUID(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['refunded_by_id'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )

    # Create indexes
    op.create_index('ix_mobile_money_payments_order_id', 'mobile_money_payments', ['order_id'])
    op.create_index('ix_mobile_money_payments_transaction_id', 'mobile_money_payments', ['transaction_id'])
    op.create_index('ix_mobile_money_payments_status', 'mobile_money_payments', ['status'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index('ix_mobile_money_payments_status', table_name='mobile_money_payments')
    op.drop_index('ix_mobile_money_payments_transaction_id', table_name='mobile_money_payments')
    op.drop_index('ix_mobile_money_payments_order_id', table_name='mobile_money_payments')
    op.drop_table('mobile_money_payments')

    # ### end Alembic commands ###
