"""add_shopping_domain

Revision ID: bfe4925baf5d
Revises: 3c017dd19c21
Create Date: 2026-06-13 15:05:56.102138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bfe4925baf5d'
down_revision: Union[str, Sequence[str], None] = '3c017dd19c21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_branding_id'), table_name='email_branding')
    op.drop_table('email_branding')
    op.drop_index(op.f('ix_email_templates_id'), table_name='email_templates')
    op.drop_index(op.f('ix_email_templates_template_key'), table_name='email_templates')
    op.drop_table('email_templates')
    op.drop_constraint(op.f('brands_slug_key'), 'brands', type_='unique')
    op.drop_index(op.f('ix_brands_id'), table_name='brands')
    op.create_index(op.f('ix_brands_is_deleted'), 'brands', ['is_deleted'], unique=False)
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_constraint(op.f('tags_slug_key'), 'tags', type_='unique')
    op.create_index(op.f('ix_tags_is_deleted'), 'tags', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tags_is_deleted'), table_name='tags')
    op.create_unique_constraint(op.f('tags_slug_key'), 'tags', ['slug'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.drop_index(op.f('ix_brands_is_deleted'), table_name='brands')
    op.create_index(op.f('ix_brands_id'), 'brands', ['id'], unique=False)
    op.create_unique_constraint(op.f('brands_slug_key'), 'brands', ['slug'], postgresql_nulls_not_distinct=False)
    op.create_table('email_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('template_key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('subject', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('preheader', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content_json', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('email_templates_pkey'))
    )
    op.create_index(op.f('ix_email_templates_template_key'), 'email_templates', ['template_key'], unique=True)
    op.create_index(op.f('ix_email_templates_id'), 'email_templates', ['id'], unique=False)
    op.create_table('email_branding',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=255), server_default=sa.text("'MyMedDevices'::character varying"), autoincrement=False, nullable=False),
    sa.Column('logo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('primary_color', sa.VARCHAR(length=7), server_default=sa.text("'#007bff'::character varying"), autoincrement=False, nullable=False),
    sa.Column('secondary_color', sa.VARCHAR(length=7), autoincrement=False, nullable=True),
    sa.Column('footer_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('contact_email', sa.VARCHAR(length=255), server_default=sa.text("'support@mymeddevices.com'::character varying"), autoincrement=False, nullable=False),
    sa.Column('website_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('social_links', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('brand_voice', sa.VARCHAR(length=100), server_default=sa.text("'professional'::character varying"), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('email_branding_pkey'))
    )
    op.create_index(op.f('ix_email_branding_id'), 'email_branding', ['id'], unique=False)
    # ### end Alembic commands ###
