"""add_wholesale_price_to_products

Revision ID: d197c342c01a
Revises: 5c078812e087
Create Date: 2026-08-11 17:18:52.912906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd197c342c01a'
down_revision: Union[str, Sequence[str], None] = '5c078812e087'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('wholesale_price', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('products', sa.Column('compare_at_price', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('products', sa.Column('has_vat', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('products', sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), server_default=sa.text('16.0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'vat_rate')
    op.drop_column('products', 'has_vat')
    op.drop_column('products', 'compare_at_price')
    op.drop_column('products', 'wholesale_price')
    # ### end Alembic commands ###
