"""add_is_clinical_pick_to_products

Revision ID: d59e7e7fcc05
Revises: af3c9ed6df28
Create Date: 2026-08-10 21:52:10.406982

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd59e7e7fcc05'
down_revision: Union[str, Sequence[str], None] = 'af3c9ed6df28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_clinical_pick', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_clinical_pick')
    # ### end Alembic commands ###
