"""Add profanity detection and moderation fields to reviews

Revision ID: d6dd9df83d7b
Revises: 20260730_add_status
Create Date: 2026-08-05 13:51:41.560879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6dd9df83d7b'
down_revision: Union[str, Sequence[str], None] = '20260730_add_status'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_reviews', sa.Column('contains_profanity', sa.Boolean(), nullable=False))
    op.add_column('product_reviews', sa.Column('flagged_words', sa.JSON(), nullable=True))
    op.add_column('product_reviews', sa.Column('moderation_status', sa.String(length=20), nullable=False))
    op.add_column('product_reviews', sa.Column('moderation_reason', sa.Text(), nullable=True))
    op.add_column('product_reviews', sa.Column('moderated_by', sa.UUID(), nullable=True))
    op.add_column('product_reviews', sa.Column('moderated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_product_reviews_contains_profanity'), 'product_reviews', ['contains_profanity'], unique=False)
    op.create_index(op.f('ix_product_reviews_moderation_status'), 'product_reviews', ['moderation_status'], unique=False)
    op.create_foreign_key(None, 'product_reviews', 'users', ['moderated_by'], ['id'], ondelete='SET NULL')
    op.drop_column('product_reviews', 'is_approved')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_reviews', sa.Column('is_approved', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'product_reviews', type_='foreignkey')
    op.drop_index(op.f('ix_product_reviews_moderation_status'), table_name='product_reviews')
    op.drop_index(op.f('ix_product_reviews_contains_profanity'), table_name='product_reviews')
    op.drop_column('product_reviews', 'moderated_at')
    op.drop_column('product_reviews', 'moderated_by')
    op.drop_column('product_reviews', 'moderation_reason')
    op.drop_column('product_reviews', 'moderation_status')
    op.drop_column('product_reviews', 'flagged_words')
    op.drop_column('product_reviews', 'contains_profanity')
    # ### end Alembic commands ###
