"""add_dashboard_preferences_to_customer_profile

Revision ID: f6bf3bd8e0a5
Revises: 35fd07218952
Create Date: 2026-06-25 22:26:22.276026

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6bf3bd8e0a5'
down_revision: Union[str, Sequence[str], None] = '35fd07218952'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_number', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'urgent', name='ticket_priority'), nullable=True),
    sa.Column('status', sa.Enum('open', 'in_progress', 'waiting_on_customer', 'resolved', 'closed', name='ticket_status'), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_reply_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    op.create_index(op.f('ix_tickets_ticket_number'), 'tickets', ['ticket_number'], unique=True)
    op.create_table('ticket_replies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Enum('yes', 'no', name='yes_no'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('customer_profiles', sa.Column('language', sa.String(length=10), nullable=False))
    op.add_column('customer_profiles', sa.Column('timezone', sa.String(length=50), nullable=False))
    op.add_column('customer_profiles', sa.Column('items_per_page', sa.Integer(), nullable=False))
    op.add_column('customer_profiles', sa.Column('default_sort', sa.String(length=50), nullable=False))
    op.add_column('customer_profiles', sa.Column('show_recently_viewed', sa.Boolean(), nullable=False))
    op.add_column('customer_profiles', sa.Column('reduced_motion', sa.Boolean(), nullable=False))
    op.add_column('customer_profiles', sa.Column('font_size', sa.String(length=20), nullable=False))
    op.add_column('customer_profiles', sa.Column('high_contrast', sa.Boolean(), nullable=False))
    op.alter_column('payment_methods', 'description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('payment_methods', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('payment_methods', 'mpesa_environment',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=True)
    op.alter_column('payment_methods', 'fee_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=True)
    op.alter_column('payment_methods', 'fee_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('payment_methods', 'fee_min',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('payment_methods', 'min_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('payment_methods', 'max_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('payment_methods', 'processing_time_seconds',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('payment_methods', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('payment_methods', 'provider_metadata',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               postgresql_using='provider_metadata::json',
               existing_nullable=True)
    op.drop_index(op.f('ix_payment_methods_id'), table_name='payment_methods')
    op.create_index(op.f('ix_payment_methods_is_deleted'), 'payment_methods', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_payment_methods_provider'), 'payment_methods', ['provider'], unique=False)
    op.create_index('ix_payment_methods_provider_status', 'payment_methods', ['provider', 'status'], unique=False)
    op.create_index(op.f('ix_payment_methods_status'), 'payment_methods', ['status'], unique=False)
    op.create_index('ix_payment_methods_status_deleted', 'payment_methods', ['status', 'is_deleted'], unique=False)
    op.drop_column('products', 'sale_price')
    op.drop_constraint(op.f('refunds_reversal_id_key'), 'refunds', type_='unique')
    op.drop_index(op.f('ix_refunds_reversal_id'), table_name='refunds')
    op.create_index(op.f('ix_refunds_reversal_id'), 'refunds', ['reversal_id'], unique=True)
    op.create_index(op.f('ix_refunds_is_deleted'), 'refunds', ['is_deleted'], unique=False)
    op.alter_column('return_requests', 'refund_method',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'original'::character varying"))
    op.drop_index(op.f('ix_return_requests_customer_id'), table_name='return_requests')
    op.create_index(op.f('ix_transactions_is_deleted'), 'transactions', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_is_deleted'), table_name='transactions')
    op.create_index(op.f('ix_return_requests_customer_id'), 'return_requests', ['customer_id'], unique=False)
    op.alter_column('return_requests', 'refund_method',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'original'::character varying"))
    op.drop_index(op.f('ix_refunds_is_deleted'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_reversal_id'), table_name='refunds')
    op.create_index(op.f('ix_refunds_reversal_id'), 'refunds', ['reversal_id'], unique=False)
    op.create_unique_constraint(op.f('refunds_reversal_id_key'), 'refunds', ['reversal_id'], postgresql_nulls_not_distinct=False)
    op.add_column('products', sa.Column('sale_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.drop_index('ix_payment_methods_status_deleted', table_name='payment_methods')
    op.drop_index(op.f('ix_payment_methods_status'), table_name='payment_methods')
    op.drop_index('ix_payment_methods_provider_status', table_name='payment_methods')
    op.drop_index(op.f('ix_payment_methods_provider'), table_name='payment_methods')
    op.drop_index(op.f('ix_payment_methods_is_deleted'), table_name='payment_methods')
    op.create_index(op.f('ix_payment_methods_id'), 'payment_methods', ['id'], unique=False)
    op.alter_column('payment_methods', 'provider_metadata',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               postgresql_using='provider_metadata::text',
               existing_nullable=True)
    op.alter_column('payment_methods', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('payment_methods', 'processing_time_seconds',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('payment_methods', 'max_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('payment_methods', 'min_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('payment_methods', 'fee_min',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('payment_methods', 'fee_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('payment_methods', 'fee_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('payment_methods', 'mpesa_environment',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('payment_methods', 'status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('payment_methods', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_column('customer_profiles', 'high_contrast')
    op.drop_column('customer_profiles', 'font_size')
    op.drop_column('customer_profiles', 'reduced_motion')
    op.drop_column('customer_profiles', 'show_recently_viewed')
    op.drop_column('customer_profiles', 'default_sort')
    op.drop_column('customer_profiles', 'items_per_page')
    op.drop_column('customer_profiles', 'timezone')
    op.drop_column('customer_profiles', 'language')
    op.drop_table('ticket_replies')
    op.drop_index(op.f('ix_tickets_ticket_number'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets')
    op.drop_table('tickets')
    # ### end Alembic commands ###
