import enum
import uuid
from datetime import UTC, datetime
from decimal import Decimal
from typing import TYPE_CHECKING, Optional

if TYPE_CHECKING:
    from app.domains.auth.models.user import User
    from app.domains.catalog.models.product import Product
    from app.domains.catalog.models.product_variant import ProductVariant
    from app.domains.logistics.models.delivery import Delivery
    from app.domains.payments.models.mobile_money_payment import MobileMoneyPayment
    from app.domains.shopping.models.sub_order import SubOrder
    from app.domains.vendor.models.vendor_offer import VendorOffer
    from app.domains.vendor.models.vendor_profile import VendorProfile

from sqlalchemy import JSON, DateTime, Float, ForeignKey, Integer, Numeric, String, text
from sqlalchemy import Enum as SQLEnum
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base
from app.domains.shared.models import AuditMixin, IDMixin


class OrderStatus(str, enum.Enum):
    """Order status."""

    PENDING = "pending"  # Order placed, awaiting processing / payment
    PAID = "paid"  # Payment received
    PROCESSING = "processing"  # Order being prepared
    SHIPPED = "shipped"  # Order shipped
    DELIVERED = "delivered"  # Order delivered
    CANCELLED = "cancelled"  # Order cancelled
    REFUNDED = "refunded"  # Refund processed (for returns/exchanges)


class Order(Base, IDMixin, AuditMixin):
    __tablename__ = "orders"

    # order_number is auto-generated by database sequence (order_number_seq)
    # The sequence is created in migration: add_order_number_sequence.py
    order_number: Mapped[int | None] = mapped_column(
        Integer, unique=True, index=True, nullable=True, server_default=text("nextval('order_number_seq')")
    )
    user_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), nullable=True, index=True
    )
    guest_token: Mapped[str | None] = mapped_column(String(100), nullable=True, index=True)
    status: Mapped[OrderStatus] = mapped_column(
        SQLEnum(OrderStatus, name="orderstatus", values_callable=lambda obj: [e.value for e in obj]),
        server_default="pending",
        default=OrderStatus.PENDING,
        nullable=False,
        index=True,
    )
    total_amount: Mapped[Decimal] = mapped_column(Numeric(12, 2), nullable=False)
    currency: Mapped[str] = mapped_column(String(3), default="KES", nullable=False)
    shipping_address: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    notes: Mapped[str | None] = mapped_column(String(500), nullable=True)
    internal_notes: Mapped[str | None] = mapped_column(String(1000), nullable=True)
    idempotency_key: Mapped[str | None] = mapped_column(String(100), unique=True, nullable=True, index=True)
    loyalty_discount: Mapped[Decimal | None] = mapped_column(Numeric(12, 2), nullable=True, default=None)
    loyalty_points_redeemed: Mapped[int | None] = mapped_column(nullable=True, default=None)
    shipping_subsidy_amount: Mapped[Decimal] = mapped_column(
        Numeric(12, 2), nullable=False, default=Decimal("0.00"), server_default="0.00"
    )

    # Relationships
    user: Mapped["User"] = relationship("User", backref="orders")
    items: Mapped[list["OrderItem"]] = relationship("OrderItem", back_populates="order", cascade="all, delete-orphan")
    sub_orders: Mapped[list["SubOrder"]] = relationship(
        "SubOrder", back_populates="parent_order", cascade="all, delete-orphan", order_by="SubOrder.created_at.asc()"
    )
    timeline_events: Mapped[list["OrderTimelineEvent"]] = relationship(
        "OrderTimelineEvent",
        back_populates="order",
        cascade="all, delete-orphan",
        order_by="OrderTimelineEvent.created_at.asc()",
    )
    mobile_money_payments: Mapped[list["MobileMoneyPayment"]] = relationship(
        "MobileMoneyPayment",
        back_populates="order",
        cascade="all, delete-orphan",
        order_by="MobileMoneyPayment.created_at.desc()",
    )
    deliveries: Mapped[list["Delivery"]] = relationship(
        "Delivery",
        back_populates="order",
        cascade="all, delete-orphan",
        order_by="Delivery.created_at.asc()",
    )

    @property
    def shipping_amount(self) -> float:
        if self.shipping_address and isinstance(self.shipping_address, dict):
            return float(self.shipping_address.get("shipping_amount", 0.0))
        return 0.0

    @property
    def packaging_fee(self) -> float:
        if self.shipping_address and isinstance(self.shipping_address, dict):
            return float(self.shipping_address.get("packaging_fee", 100.0))
        return 100.0

    @property
    def services_fee(self) -> float:
        if self.shipping_address and isinstance(self.shipping_address, dict):
            return float(self.shipping_address.get("services_fee", 50.0))
        return 50.0

    @property
    def tax_amount(self) -> float:
        if self.shipping_address and isinstance(self.shipping_address, dict):
            return float(self.shipping_address.get("tax_amount", 0.0))
        return 0.0

    @property
    def discount_amount(self) -> float:
        if self.shipping_address and isinstance(self.shipping_address, dict):
            return float(self.shipping_address.get("discount_amount", 0.0))
        return 0.0

    @property
    def subtotal(self) -> float:
        if self.items:
            return float(sum(float(item.subtotal) for item in self.items))
        if self.shipping_address and isinstance(self.shipping_address, dict):
            return float(self.shipping_address.get("subtotal", 0.0))
        return 0.0

    @property
    def payment_method(self) -> str:
        if self.shipping_address and isinstance(self.shipping_address, dict):
            return self.shipping_address.get("payment_method", "cod")
        return "cod"

    @property
    def payment_method_title(self) -> str:
        if self.shipping_address and isinstance(self.shipping_address, dict):
            pm_title = self.shipping_address.get("payment_method_title")
            if pm_title:
                return pm_title
            pm = self.shipping_address.get("payment_method", "cod")
            return "M-Pesa Express" if pm == "mpesa" else "Cash on Delivery"
        return "Cash on Delivery"

    @property
    def mobile_money_payment(self) -> Optional["MobileMoneyPayment"]:
        """Get the most recent active mobile money payment for this order."""
        if not self.mobile_money_payments:
            return None
        # Return the most recent non-refunded payment
        from app.domains.payments.models.mobile_money_payment import MobileMoneyPaymentStatus

        for payment in self.mobile_money_payments:
            if payment.status != MobileMoneyPaymentStatus.REFUNDED:
                return payment
        return None

    def __repr__(self):
        return f"<Order(id={self.id}, status={self.status}, total={self.total_amount})>"


class OrderTimelineEvent(Base, IDMixin):
    __tablename__ = "order_timeline_events"

    order_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("orders.id", ondelete="CASCADE"), nullable=False, index=True)
    status: Mapped[str] = mapped_column(String(50), nullable=False, index=True)
    message: Mapped[str] = mapped_column(String(500), nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(UTC), nullable=False
    )
    created_by: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("users.id", ondelete="SET NULL"), nullable=True)

    # Relationships
    order: Mapped["Order"] = relationship("Order", back_populates="timeline_events")


class OrderItemFulfillmentStatus(str, enum.Enum):
    """Status of an individual order item fulfillment."""

    PENDING = "pending"
    PROCESSING = "processing"
    PACKED = "packed"
    SHIPPED = "shipped"
    DELIVERED = "delivered"
    CANCELLED = "cancelled"
    REFUNDED = "refunded"


class OrderItem(Base, IDMixin):
    __tablename__ = "order_items"

    order_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("orders.id", ondelete="CASCADE"), nullable=False, index=True)
    sub_order_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("sub_orders.id", ondelete="CASCADE"), nullable=True, index=True
    )
    product_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("products.id"), nullable=False, index=True)
    product_variant_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("product_variants.id", ondelete="SET NULL"), nullable=True, index=True
    )
    vendor_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("vendor_profiles.id"), nullable=False, index=True)
    vendor_offer_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("vendor_offers.id", ondelete="SET NULL"), nullable=True, index=True
    )
    quantity: Mapped[float] = mapped_column(Float, nullable=False)
    unit_price: Mapped[Decimal] = mapped_column(Numeric(12, 2), nullable=False)
    subtotal: Mapped[Decimal] = mapped_column(Numeric(12, 2), nullable=False)

    # Pricing & tax snapshots captured at order time
    pricing_rule_version: Mapped[str | None] = mapped_column(String(20), nullable=True, default="v1.0")
    vendor_price_snapshot: Mapped[Decimal | None] = mapped_column(Numeric(12, 2), nullable=True)
    markup_amount_snapshot: Mapped[Decimal | None] = mapped_column(Numeric(12, 2), nullable=True)
    commission_amount_snapshot: Mapped[Decimal | None] = mapped_column(Numeric(12, 2), nullable=True)
    unit_customer_price_snapshot: Mapped[Decimal | None] = mapped_column(Numeric(12, 2), nullable=True)
    bundle_discount_allocated_snapshot: Mapped[Decimal] = mapped_column(
        Numeric(12, 2), nullable=False, default=Decimal("0.00"), server_default="0.00"
    )
    net_unit_customer_price_snapshot: Mapped[Decimal | None] = mapped_column(Numeric(12, 2), nullable=True)
    tax_category_code: Mapped[str | None] = mapped_column(
        String(50), nullable=True, default="STANDARD_VAT_16", server_default="STANDARD_VAT_16"
    )
    tax_rate_snapshot: Mapped[Decimal | None] = mapped_column(
        Numeric(5, 2), nullable=True, default=Decimal("0.00"), server_default="0.00"
    )
    tax_amount_snapshot: Mapped[Decimal | None] = mapped_column(
        Numeric(12, 2), nullable=True, default=Decimal("0.00"), server_default="0.00"
    )
    selling_unit_snapshot: Mapped[str | None] = mapped_column(
        String(20), nullable=True, default="PIECE", server_default="PIECE"
    )
    package_quantity_snapshot: Mapped[int | None] = mapped_column(
        Integer, nullable=True, default=1, server_default="1"
    )

    # Fulfillment fields for per-item tracking
    fulfillment_status: Mapped[str] = mapped_column(
        String(20), default=OrderItemFulfillmentStatus.PENDING.value, nullable=False, index=True
    )
    tracking_number: Mapped[str | None] = mapped_column(String(100), nullable=True)
    tracking_url: Mapped[str | None] = mapped_column(String(500), nullable=True)

    # Relationships
    order: Mapped["Order"] = relationship("Order", back_populates="items")
    sub_order: Mapped[Optional["SubOrder"]] = relationship("SubOrder", back_populates="items")
    product: Mapped["Product"] = relationship("Product")
    product_variant: Mapped[Optional["ProductVariant"]] = relationship("ProductVariant")
    vendor_offer: Mapped[Optional["VendorOffer"]] = relationship("VendorOffer")
    vendor: Mapped["VendorProfile"] = relationship("VendorProfile")

    @property
    def product_name(self) -> str:
        return self.product.name if self.product else "Unknown Product"

    @property
    def total_price(self) -> float:
        return float(round(self.subtotal))

    @property
    def sku(self) -> str:
        return self.product.sku or "N/A" if self.product else "N/A"

    @property
    def total(self) -> float:
        return float(round(self.subtotal))

    @property
    def status(self) -> str:
        return self.fulfillment_status

    def __repr__(self):
        return f"<OrderItem(id={self.id}, order_id={self.order_id}, product_id={self.product_id})>"
